### ISSUE TITLE
Running trackalyzer gives `IndexError: list index out of range`

### ISSUE THREAD

**Issue by unbeatable-101** [khimaros/trackalyzer#1]
```
williamdavis@Williams-Air ~ % trackalyzer 
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/bin/trackalyzer", line 8, in <module>
    sys.exit(run())
  File "/opt/homebrew/lib/python3.9/site-packages/trackalyzer/cli.py", line 91, in run
    gpxpath = sys.argv[1]
IndexError: list index out of range
```

**Comment by khimaros** [comment]
@unbeatable-101 -- it looks like you're using an old version. pull from git or make sure you are on release `>=0.1.2` from PyPi
